config/routes.rb
BMIExo::Application.routes.draw do
  
  get "users/new"
  resources :posts, path: 'news'
  resources :researches, path: 'research'
  resources :publications
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root 'welcome#index'
  match '/people',       to: 'welcome#people',    via: 'get'
  match '/news',         to: 'posts#index',        via: 'get'
  
  match '/contact',      to: 'welcome#contact',   via: 'get'
  match '/signin',       to: 'sessions#new',      via: 'get'
  match '/signout',      to: 'sessions#destroy',  via: 'delete'
  
  

   

  

end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :title, presence: true, length:{minimum:5}
	validates :text, presence: true, length:{minimum:15}
	
end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/models/research.rb
class Research < ActiveRecord::Base

	validates :title, presence: true, length:{minimum:5}
	validates :text, presence: true, length:{minimum:15}
	has_attached_file :rAttachment

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save {self.email = email.downcase}
	before_create :create_remember_token
	
	#VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i  Formats it so email is required
	validates :email, presence:true, uniqueness:{case_sensitive:false} #,format: {with:VALID_EMAIL_REGEX}
	has_secure_password
	validates :password, length: { minimum: 6}
	
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end
	
	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end
	
	private
	
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	def new
		@post = Post.new
	end
	
	def index
		@posts =Post.all(:order => "created_at DESC")
	end
	
	def create
		@post = Post.new(params[:post].permit( :title , :text))
		
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end
	
	def show
		@post =Post.find(params[:id])
	end
	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		
		redirect_to posts_path
	end
	
	def edit
		@post = Post.find(params[:id])
	end
	
	def update
		@post = Post.find(params[:id])
		
		if @post.update(params[:post].permit(:title,:text))
			redirect_to @post
		else
			render 'edit'
		end
	end
	
	private
		def post_params
			params.require(:post).permit( :title , :text)
		end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
	
	def new
		@publication = Publication.new
	end
	
	def index
		@publications =Publication.all(:order => "created_at DESC")
	end
	
	def create
		@publication = Publication.new(params[:publication].permit( :title , :text))
		
		if @publication.save
			redirect_to @publication
		else
			render 'new'
		end
	end
	
	def show
		@publication =Publication.find(params[:id])
	end
	
	def destroy
		@publication = Publication.find(params[:id])
		@publication.destroy
		
		redirect_to publications_path
	end
	
	def edit
		@publication = Publication.find(params[:id])
	end
	
	def update
		@publication = Publication.find(params[:id])
		
		if @publication.update(params[:publication].permit(:title,:text))
			redirect_to @publication
		else
			render 'edit'
		end
	end
	
	private
		def publication_params
			params.require(:publication).permit( :title , :text)
		end
end

app/controllers/researches_controller.rb
class ResearchesController < ApplicationController
def new
		@research = Research.new
	end
	
	def index
		@researches =Research.all(:order => "created_at DESC")
	end
	
	def create
		@research = Research.new(params[:research].permit( :title , :text , :rAttachment))
		
		if @research.save
			redirect_to @research
		else
			render 'new'
		end
	end
	
	
	def show
		@research =Research.find(params[:id])
	end
	
	def destroy
		@research = Research.find(params[:id])
		@research.destroy
		
		redirect_to researches_path
	end
	
	def edit
		@research = Research.find(params[:id])
	end
	
	def update
		@research = Research.find(params[:id])
		
		if @research.update(params[:research].permit(:title,:text,:rAttachment))
			redirect_to @research
		else
			render 'edit'
		end
	end
	
	private
		def research_params
			params.require(:research).permit( :title , :text, :rAttatchment)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
	user = User.find_by(email: params[:session][:email].downcase)
	if user && user.authenticate(params[:session][:password])
		sign_in user
		redirect_to root_url
	else
		flash.now[:error] = 'Invalid email/password combination'
		render 'new'
	end
end

def destroy
	sign_out
	redirect_to root_url
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
	@user = User.new
  end
  
  
  def create
	@user = User.new(user_params)
	if @user.save
		sign_in @user
		redirect_to root_url
	else
		render 'new'
	end
  end
  
  private
	
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def contact
  end
  
  def people
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end
	
	def signed_in?
		!current_user.nil?
	end
	
	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
	
	def current_user=(user)
		@current_user = user
	end
	
	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<%= image_tag("nih_logo.png", :class=>"logo")  %>
	<small>
		Grant Number: 5R01NS081854-02 
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="title">
	<div class="mainTitle">
		<h1>BMI Control of a Therapeutic Exoskeleton</h1>
	</div>

	<div class="secondTitle">
			<h2>The BMI-Exo Project: Facilitating Personalized Robotic Rehabilitation of the Upper Limb</h>
	</div>
</div>
	
<header class="mainHeader">
	<nav>
		<ul>
			<li class="home"><%= link_to "Home", root_path, class:"linkText"  %></li>
			<li class="people"><%= link_to "People", people_path, class:"linkText" %></li>
			<li class="news"> <%= link_to "News", news_path, class:"linkText"  %></li>
			<li class="research"><%= link_to "Research", researches_path, class:"linkText"  %></li>
			<li class="publications"> <%= link_to "Publications", publications_path, class:"linkText"  %></li>
			<li class="contact"><%= link_to "Contact", contact_path, class:"linkText"  %></li>
			<% if signed_in? %>
				<li><%= link_to "Sign Out", signout_path, method:"delete", class:"linkText"  %></li>
			<% else %>
				<li class="signIn"><%= link_to "Sign In", signin_path, class:"linkText"  %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>BMI-Exo Projects | <%= yield(:title) %></title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <%= render 'layouts/shim.html.erb' %>
	</head>
	<body id="<%= yield(:title) %>">
		<%= render 'layouts/header.html.erb' %>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer.html.erb' %>
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errorExplanation">
			<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved: </h2>
			<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</ div>
	<% end %>
	
	<p>
		<%=f.label :title %> <br>
		<%=f.text_field :title %>
	</p>

	<p>
		<%=f.label :text %> <br>
		<%=f.text_area :text, size:"60x12" %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "Edit News") %>

<div class="contentNews">
	<div class="header">
		<h2>Editing Post </h2>
	</div>
	<div class="form">
		<%= render 'form' %>
	</div>
	<div class="options">
		<%= link_to 'Back', posts_path, class:"full"  %>
	</div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "News") %>
<div id="addNews">
	<% if signed_in? %>
		<%= link_to "Add News", new_post_path, id:"linkAdd" %>
	<% end %>
</div>
<div class="header">
	<h2>News</h2>
</div>


<% @posts.each do |post| %>
	<div class="contentNews">
		<div class="newsTitle">
			<%= post.title  %>
		</div>
		<div class="article">
			<%= truncate(post.text, :separator =>". ", :length => 410, :omission => ". (full text below)") %>
		</div>
		<br>
		<div class="options">
			<%= link_to "Full-Text", post_path(post), class:"full" %>
			<% if signed_in? %>
				<%= link_to "Destroy", post_path(post), method: :delete, data:{confirm:"Are you sure?"}, class:"changeLink" %>
				<%= link_to "Edit", edit_post_path(post), class:"changeLink" %>
			<% end %>
		</div>
	</div>
<%end %>

app/views/posts/new.html.erb
<% provide(:title, "Add News") %>

<div class="header">
	<h2>Add News</h2>
</div>

<div class="contentNews">
	
	<div class="form">
		<%= render 'form' %>
	</div>
	<div class="options">
		<%= link_to 'Back', posts_path, class:"full" %>
	</div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "Full News") %>

<div class="contentNews">
	<div class="newsTitle">
		<%= @post.title  %>
	</div>
	<div class="article">
		<%= @post.text %>
	</div>
	<br>
	<div class="options">
		<%= link_to "Back", posts_path, class:"full"  %>
		<% if signed_in? %>
			<%= link_to "Edit", edit_post_path(@post), class:"changeLink"  %>
		<% end %>
	</div>
</div>

app/views/publications/_form.html.erb
<%= form_for @publication do |f| %>
	<% if @publication.errors.any? %>
		<div id="errorExplanation">
			<h2><%= pluralize(@publication.errors.count, "error") %> prohibited this post from being saved: </h2>
			<ul>
			<% @publication.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</ div>
	<% end %>
	
	<p>
		<%=f.label :title %> <br>
		<%=f.text_field :title %>
	</p>

	<p>
		<%=f.label :text %> <br>
		<%=f.text_area :text, size:"60x12" %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/publications/edit.html.erb
<% provide(:title, "Edit Publications") %>

<div class="contentPublication">
	<div class="header">
		<h2>Editing Publication </h2>
	</div>
	<div class="form">
		<%= render 'form' %>
	</div>
	<div class="options">
		<%= link_to 'Back', publications_path, class:"full"  %>
	</div>
</div>

app/views/publications/index.html.erb
<% provide(:title, "Publications") %>
<div id="addPublication">
	<% if signed_in? %>
		<%= link_to "Add Publication", new_publication_path, id:"linkAdd" %>
	<% end %>
</div>
<div class="header">
	<h2>Publications</h2>
</div>


<% @publications.each do |publication| %>
	<div class="contentPublication">
		<div class="publicationTitle">
			<%= publication.title  %>
		</div>
		<div class="article">
			<%= truncate(publication.text, :separator =>". ", :length => 410, :omission => ". (full text below)") %>
		</div>
		<br>
		<div class="options">
			<%= link_to "Full-Text", publication_path(publication), class:"full" %>
			<% if signed_in? %>
				<%= link_to "Destroy", publication_path(publication), method: :delete, data:{confirm:"Are you sure?"}, class:"changeLink" %>
				<%= link_to "Edit", edit_publication_path(publication), class:"changeLink" %>
			<% end %>
		</div>
	</div>
<%end %>

app/views/publications/new.html.erb
<% provide(:title, "Add Publication") %>

<div class="header">
	<h2>Add Publication</h2>
</div>

<div class="contentPublication">
	
	<div class="form">
		<%= render 'form' %>
	</div>
	<div class="options">
		<%= link_to 'Back', publications_path, class:"full" %>
	</div>
</div>

app/views/publications/show.html.erb
<% provide(:title, "Full Publication") %>

<div class="contentPublication">
	<div class="publicationTitle">
		<%= @publication.title  %>
	</div>
	<div class="article">
		<%= @publication.text %>
	</div>
	<br>
	<div class="options">
		<%= link_to "Back", publications_path, class:"full"  %>
		<% if signed_in? %>
			<%= link_to "Edit", edit_publication_path(@publication), class:"changeLink"  %>
		<% end %>
	</div>
</div>

app/views/researches/_form.html.erb
<%= form_for @research, :html => { :multipart => true } do |f| %>

	<% if @research.errors.any? %>
		<div id="errorExplanation">
			<h2><%= pluralize(@research.errors.count, "error") %> prohibited this post from being saved: </h2>
			<ul>
			<% @research.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</ div>
	<% end %>
	
	<p>
		<!--<= f.label :rAttachment %>
		<= f.file_field :rAttachment %> used to attach image to the post, add % for it to work-->
		
		<%= f.label :title %> <br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%=f.label :text %> <br>
		<%=f.text_area :text, size:"60x12" %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/researches/edit.html.erb
<% provide(:title, "Edit Research") %>

<div class="contentResearch">
	<div class="header">
		<h2>Editing Research </h2>
	</div>
	<div class="form">
		<%= render 'form' %>
	</div>
	<div class="options">
		<%= link_to 'Back', researches_path, class:"full"  %>
	</div>
</div>

app/views/researches/index.html.erb
<% provide(:title, "Research") %>
<div id="addResearch">
	<% if signed_in? %>
		<%= link_to "Add Research", new_research_path, id:"linkAdd" %>
	<% end %>
</div>
<div class="header">
	<h2>Research</h2>
</div>


<% @researches.each do |research| %>
	<div class="contentResearch">
		<!--<div class="rPicture">
			< if research.rAttachment.exists? then %>
				<= image_tag research.rAttachment.url %>
			< else %>
				<p> Please add a Research Photo <p>
			< end %>
		</div>			Need to add % to each statement if we want to add pictures to research-->
		<div class="researchTitle">
			<%= research.title  %>
		</div>
		<div class="article">
			<%= truncate(research.text, :separator =>". ", :length => 410, :omission => ". (full text below)") %>
		</div>
		<br>
		<div class="options">
			<%= link_to "Full-Text", research_path(research), class:"full" %>
			<% if signed_in? %>
				<%= link_to "Destroy", research_path(research), method: :delete, data:{confirm:"Are you sure?"}, class:"changeLink" %>
				<%= link_to "Edit", edit_research_path(research), class:"changeLink" %>
			<% end %>
		</div>
	</div>
<%end %>

app/views/researches/new.html.erb
<% provide(:title, "Add Research") %>

<div class="header">
	<h2>Add Research</h2>
</div>

<div class="contentResearch">
	<div class="form">
		<%= render 'form' %>
	</div>
	<div class="options">
		<%= link_to 'Back', researches_path, class:"full" %>
	</div>
</div>

app/views/researches/show.html.erb
<% provide(:title, "Full Research") %>

<div class="contentResearch">
	<div class="researchTitle">
		<%= @research.title  %>
	</div>
	<div class="article">
		<%= @research.text %>
		<!--<= image_tag @research.rAttachment.url %> need to add % to make image tag work-->
	</div>
	<br>
	<div class="options">
		<%= link_to "Back", researches_path, class:"full"  %>
		<% if signed_in? %>
			<%= link_to "Edit", edit_research_path(@research), class:"changeLink"  %>
		<% end %>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="errorExplanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this account from being saved: </h2>
			<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</ div>
	<% end %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<div class="header"> 
	<h2>Sign Up</h2>
</div>

<div class="mainContent">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		<div class= "subContLabel">
			<%= f.label :username %>
		</div>
		<div class= "subContText">
			<%= f.text_field :email %><br><br>
		</div>
		
		<div class= "subContLabel1">
			<%= f.label :password %>
		</div>
		<div class= "subContText1">
			<%= f.password_field :password %><br><br>
		</div>
		
		<div class= "subContLabel2">
			<%= f.label :password_confirmation, "Confirmation" %>
		</div>
		<div class= "subContText2">
			<%= f.password_field :password_confirmation %><br>
		</div>
		
		<div class= "subContButton">		
			<%= f.submit "Submit" %>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>

<%= @user.email %>

app/views/welcome/contact.html.erb
<% provide(:title, "Contact") %>

<div class="header">
	<h2>Contact Information</h2>
</div>
<div class="mainContent">
	<span><span style="text-decoration: underline; font-size: medium;"><strong>MAHI Lab</strong></span>
	</span>
	<p>
		To contact the Mechatronics and Haptics Lab at Rice University, please visit the MAHI Lab's
		<a href="http://mahilab.rice.edu/" target="blank">website</a>.
	</p>

	<span style="text-decoration: underline; font-size: medium;"><strong>Brain-Machine Interface Systems Team</strong></span>
	<p>	
		To contact the Brain-Machine Interface Systems Team at the University of Houston, please visit the Team's <a href="http://uhbmist.tumblr.com/" target="blank">tumblr</a> or <a href="https://www.facebook.com/UHBMIST" target="blank">facebook</a> page.
	</p>
</div>

app/views/welcome/index.html.erb
<% provide(:title, "Home") %>

<div class="header">
	<h2>The BMI-Exo Project</h2>
</div>

<div class="mainContent">
	<p>
		The BMI-Exo Project is a research collaboration between Rice University, the University of Houston, the University of Texas Health Science Center, and the Methodist Hospital  that aims to accelerate the development, efficacy and use of robotic rehabilitation after stroke. By combining a noninvasive brain-machine interface (BMI) with a robotic rehabilitation exoskeleton, the therapy is now ‘active’ and the patients  across a broad spectrum of impairment are engaged in the rehabilitation tasks. When complete, the combined device will be validated by UTHealth physicians at TIRR Memorial Hermann with as many as 40 volunteer patients. Together, the team hopes to increase the upper limb function for stroke patients, advance the understanding of brain plasticity, and help innovate rehabilitation. For more information about this project please visit our project’s NIH Report page by clicking <a href="//projectreporter.nih.gov/project_info_description.cfm?aid=8459096&amp;icde=16706923&amp;ddparam=&amp;ddvalue=&amp;ddsub=&amp;cr=1&amp;csb=default&amp;cs=ASC" target="blank">here</a>.
	</p>
</div>

<div class="mainImage">
	<%= image_tag("bmi-exo_main.jpg") %>
</div>

<div class="bottomImages">
	<div class="image">
		<%= image_tag("rice_logo.jpg") %>
	</div>
	<div class="image">
		<%= image_tag("UH_logo.jpg") %>
	</div>
	<div class="image">
		<%= image_tag("UT_logo.jpg") %>
	</div>
	<div class="image">
	<%= image_tag("Methodist_logo.jpg") %>
	</div>
</div>

app/views/welcome/people.html.erb
<% provide(:title, "People") %>

<div class="header">
	<h2>People</h2>
</div>

<div class="mainContent">
	<table>
		<tbody>
			<tr>
				<td>
					<div class ="portrait">
						<%= image_tag("omalley_image.jpg") %>
					</div>
				</td>
				<td>
					<p class="textCol">
						Marcia O'Malley<br>
						Principal Investigator<br>
						Rice University<br>
						omalleym@rice.edu<br>
						<a href="https://memsweb.rice.edu/omalley/" target="blank">Personal Webpage</a>
					</p>
				</td>
				<td class="filler">
				</td>
				<td>
					<div class ="portrait">
						<%= image_tag("vidal_image.jpg") %>
					</div>
				</td>
				<td> 
					<p class="textCol">
						Jose Contreras-Vidal<br>
						Principal Investigator<br>
						University of Houston<br>
						jlcontreras-vidal@uh.edu<br>
						<a href="http://www.ee.uh.edu/faculty/contreras-vidal" target="blank">Personal Webpage</a>
					</p>
				</td>
			</tr>
			
		<!--Second row-->
			<tr>
				<td>
					<div class ="portrait">
						<%= image_tag("francisco_image.jpg") %>
					</div>
				</td>
				<td>
					<p class="textCol">
						Gerard Francisco<br>
						Principal Investigator<br>
						UTHSC<br>
						Gerard.E.Francisco@uth.tmc.edu<br>
						<a href="http://www.uth.tmc.edu/schools/med/phymed/faculty/bio-Francisco-Gerard.html" target="blank">Personal Webpage</a>
					</p>
				</td>
				<td class="filler">
				</td>
				<td>
					<div class ="portrait">
						<%= image_tag("grossman_image.jpg") %>
					</div>
				</td>
				<td> 
					<p class="textCol">
						Robert Grossman<br>
						Co-Investigator<br>
						Methodist Hospital<br>
						rgrossman@tmhs.org<br>
						<a href="http://www.methodisthealth.com/tmhri.cfm?id=36309" target="blank">Personal Webpage</a>
					</p>
				</td>
			</tr>
			
		<!--Third row -->
			<tr>
				<td>
					<div class ="portrait">
						<%= image_tag("yozbatiran_image.jpg") %>
					</div>
				</td>
				<td>
					<p class="textCol">
						Nuray Yozbatiran<br>
						Co-Investigator<br>
						UTHSC<br>
						Nuray.Yozbatiran@uth.tmc.edu
					</p>
				</td>
				<td class="filler">
				</td>
				<td>
					<div class ="portrait">
						<%= image_tag("joseph_image.jpg") %>
					</div>
				</td>
				<td> 
					<p class="textCol">
						Prathap Joseph<br>
						Co-Investigator<br>
						UTHSC<br>
						Prathap.J.Joseph@uth.tmc.edu
					</p>
				</td>
			</tr>
			
		<!-- Fourth row -->
			<tr>
				<td>
					<div class ="portrait">
						<%= image_tag("Anusha_image.jpg") %>
					</div>
				</td>
				<td>
					<p class="textCol">
						Dr. Anusha Venkatakrishnan<br>
						Co-Investigator<br>
						University of Houston<br>
						avenkatakrishnan@uh.edu
					</p>
				</td>
				<td class="filler">
				</td>
				<td>
					<div class ="portrait">
						<%= image_tag("amy_image.jpg") %>
					</div>
				</td>
				<td> 
					<p class="textCol">
						Amy Blank<br>
						Postdoctoral Fellow<br>
						Rice University<br>
						aab14@rice.edu
					</p>
				</td>
			</tr>
			
		<!-- Fifth row -->
			<tr>
				<td>
					<div class ="portrait">
						<%= image_tag("french_image.png") %>
					</div>
				</td>
				<td>
					<p class="textCol">
						James French<br>
						Graduate Student<br>
						Rice University<br>
						jfrench0812@gmail.com
					</p>
				</td>
				<td class="filler">
				</td>
				<td>
					<div class ="portrait">
						<%= image_tag("bhagat_image.jpg") %>
					</div>
				</td>
				<td> 
					<p class="textCol">
						Nikunj Bhagat<br>
						Graduate Student<br>
						University of Houston<br>
						nabhagat@uh.edu
					</p>
				</td>
			</tr>
			
		<!-- Sixth row -->
			<tr>
				<td>
					<div class ="portrait">
						<%= image_tag("li_image.jpg") %>
					</div>
				</td>
				<td>
					<p class="textCol">
						Liyang Li<br>
						Research Assistant<br>
						University of Houston<br>
			<!-- no email-->
					</p>
				</td>
				<td class="filler">
				</td>
				<td>
					<div class ="portrait">
					</div>
				</td>
				<td> 
					<p class="textCol">
					</p>
				</td>
			</tr>
		</tbody>
	</table>
</div>